name: ElementalSpears
main: me.minetwice.elementalspears.ElementalSpears
version: 1.0.0
api-version: 1.21
author: minetwice
commands:
  getspear:
    description: Get all elemental spears.
    usage: /getspear
    permission: elementalspears.getspear
  clearcords:
    description: Clear coords reveal for a player.
    usage: /clearcords <player>
    permission: elementalspears.admin
  clearspear:
    description: Remove all spears from a player.
    usage: /clearspear <player>
    permission: elementalspears.admin
permissions:
  elementalspears.admin:
    description: Allows admin commands.
    default: op
  elementalspears.getspear:
    description: Get all spears.
    default: true
